name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Test Go linting (gofmt)
        if: startsWith(matrix.os, 'ubuntu') == true
        run: gofmt -s -w . && git diff --exit-code
      - name: Run Go tests
        run: go test -p 1 ./ -v
